// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/specularL2/specular/services/sidecar/internal/service/config"
	"github.com/specularL2/specular/services/sidecar/internal/sidecar/api"
)

// Injectors from inject.go:

func SetupApplication() (*Application, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	app, err := api.NewCli(configConfig)
	if err != nil {
		return nil, nil, err
	}
	logger := config.NewLogger(configConfig)
	cancelChannel := config.NewCancelChannel()
	context := config.NewContext(logger, cancelChannel)
	application := &Application{
		cli:    app,
		ctx:    context,
		log:    logger,
		config: configConfig,
	}
	return application, func() {
	}, nil
}

func SetupApplicationForIntegrationTests(cfg *config.Config) (*TestApplication, func(), error) {
	app, err := api.NewCli(cfg)
	if err != nil {
		return nil, nil, err
	}
	logger := config.NewLogger(cfg)
	cancelChannel := config.NewCancelChannel()
	context := config.NewContext(logger, cancelChannel)
	application := &Application{
		cli:    app,
		ctx:    context,
		log:    logger,
		config: cfg,
	}
	testApplication := &TestApplication{
		Application: application,
		Ctx:         context,
		Log:         logger,
		Config:      cfg,
	}
	return testApplication, func() {
	}, nil
}
