apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.specular.network/sp-network: "true"
    io.specular.service: generator
  name: generator
spec:
  containers:
    - name: generator
      command: ["bash", "-c", "{{ .Values.generator.command }}"]
      image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
      resources:
        {{- .Values.default_resources |  toYaml | nindent 10 }}
      volumeMounts:
        - mountPath: {{ .Values.volume.efs.mountPath }}
          name: {{ .Values.volume.efs.name }}
{{- range $i, $value := .Values.volume.configVolumeMounts.paths }}
        - name: {{ $.Values.volume.configVolumeMounts.name }}
          mountPath: {{ $.Values.volume.efs.mountPath }}/{{ $value }}
          subPath: {{ $value }}
{{- end }}
  {{- range $i, $value := .Values.volume.secrets }}
        - name: secret-volume
          mountPath: {{ $.Values.volume.efs.mountPath }}/{{ $value.file }}
          subPath: {{ $value.file }}
          readOnly: true
{{- end }}
      lifecycle:
        preStop:
          exec:
            command: ["sh", "-c", "rm -f /specular/workspace/.*.lock"]
  restartPolicy: Never
  volumes:
    - name: {{ .Values.volume.efs.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.volume.efs.name }}
    - name: {{ .Values.volume.configVolumeMounts.name }}
      configMap:
        name: {{ .Values.volume.configVolumeMounts.name }}
    - name: secret-volume
      secret:
        secretName: l2-secrets
status: {}
