# syntax=docker/dockerfile:1

FROM golang:1.17-alpine

RUN apk add --no-cache git
RUN apk add --no-cache yarn

# USER golang
WORKDIR /
COPY clients/geth/specular .
COPY contracts .

# RUN yarn install

RUN go generate ./...
# RUN cd /cmd/geth
RUN go build -o /build/bin/geth ./cmd/geth

# COPY go.mod ./
# RUN go mod download
# COPY *.go ./
# RUN go build -o /godocker

EXPOSE 8080

CMD [ "/godocker" ]⏎