#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd contracts
pnpm lint-staged

cd ..

SIDECAR_DIR="services/sidecar"
if git diff --cached --quiet -- "$SIDECAR_DIR"; then
    echo "No Changes Found in $SIDECAR_DIR, skipping `make install`"
else
    echo "Changes found in $SIDECAR_DIR"
    make install
    echo "Successfully ran `make install`"
fi
