#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd contracts
pnpm lint-staged
cd ..

SIDECAR_DIR="services/sidecar"
if git diff --cached --quiet -- "$SIDECAR_DIR"; then
    echo "No changes found in $SIDECAR_DIR, skipping `make`"
else
    echo "Changes found in $SIDECAR_DIR"
    make
    echo "Successfully ran `make`"
fi
